### ISSUE TITLE
Include transform-object-assign and  array-includes

### ISSUE THREAD

**Issue by kylezeeuwen** [jmcriffey/babel-preset-es2015-ie#1]
Hello,

Thanks for the code!

I've found that I needed to include `transform-object-assign` and  `array-includes` in addition to the plugins specified by `babel-preset-es2015-ie` in order to get working code in IE.

Does it make sense to update `babel-preset-es2015-ie` to include them ? If so I can put a PR together.

**Comment by JessicaSachs** [comment]
Bump ^

**Comment by VovanR** [comment]
@kylezeeuwen `Array.prototype.includes()` in es2016, not es2015

**Comment by jeffrifwald** [comment]
Object-assign has been added and published in `6.7.0`. I agree that `Array.includes` is out of scope of this repo. Thanks!

**Comment by kylezeeuwen** [comment]
Thanks !
